In [15]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import decimal
from __future__ import division
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

# Read the training and testing data. Print the number of features in the dataset.
#   https://archive.ics.uci.edu/ml/datasets/Breast+Cancer+Wisconsin+(Diagnostic)
Wisconsin_Breast_cancer_test = pd.read_csv("../../../../datasets/wbcd_test.csv")
Wisconsin_Breast_cancer_train = pd.read_csv("../../../../datasets/wbcd_train.csv")

### List features
test_features = Wisconsin_Breast_cancer_test.shape[1]
train_features = Wisconsin_Breast_cancer_train.shape[1]
print("number of test features: %d" % test_features)
print("number of training features: %d" % train_features)

Wisconsin_Breast_cancer_train.head()

number of test features: 32
number of training features: 32

,Patient_ID,Diagnosis,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,f13,f14,f15,f16,f17,f18,f19,f20,f21,f22,f23,f24,f25,f26,f27,f28,f29,f30
0,909410,B,14.02,15.66,89.59,606.5,0.07966,0.05581,0.02087,0.02652,0.1589,0.05586,0.2142,0.6549,1.606,19.25,0.004837,0.009238,0.009213,0.010760,0.01171,0.002104,14.91,19.31,96.53,688.9,0.10340,0.1017,0.06260,0.08216,0.2136,0.06710
1,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,0.7572,0.7813,5.438,94.44,0.011490,0.024610,0.056880,0.018850,0.01756,0.005115,22.54,16.67,152.20,1575.0,0.13740,0.2050,0.40000,0.16250,0.2364,0.07678
2,8912284,B,12.89,15.70,84.08,516.6,0.07818,0.09580,0.11150,0.03390,0.1432,0.05935,0.2913,1.3890,2.347,23.29,0.006418,0.039610,0.079270,0.017740,0.01878,0.003696,13.90,19.69,92.12,595.6,0.09926,0.2317,0.33440,0.10170,0.1999,0.07127
3,90317302,B,10.26,12.22,65.75,321.6,0.09996,0.07542,0.01923,0.01968,0.1800,0.06569,0.1911,0.5477,1.348,11.88,0.005682,0.013650,0.008496,0.006929,0.01938,0.002371,11.38,15.65,73.23,394.5,0.13430,0.1650,0.08615,0.06696,0.2937,0.07722
4,914102,B,13.16,20.54,84.06,538.7,0.07335,0.05275,0.01800,0.01256,0.1713,0.05888,0.3237,1.4730,2.326,26.07,0.007802,0.020520,0.013410,0.005564,0.02086,0.002701,14.50,28.46,95.29,648.3,0.11180,0.1646,0.07698,0.04195,0.2687,0.07429

In [16]:
# Data label is B or M in "Diagnosis", convert to 1 and 0, B = 1, M = 0
breastCancertest = Wisconsin_Breast_cancer_test.Diagnosis == 'B'
malignantTest = Wisconsin_Breast_cancer_test.Diagnosis == 'M'
breastCancertrain = Wisconsin_Breast_cancer_train.Diagnosis == 'B'
malignantTrain = Wisconsin_Breast_cancer_train.Diagnosis == 'M'
column_name = 'Diagnosis'
Wisconsin_Breast_cancer_test.loc[breastCancertest, column_name] = 1
Wisconsin_Breast_cancer_test.loc[malignantTest, column_name] = 0
Wisconsin_Breast_cancer_train.loc[breastCancertrain, column_name] = 1
Wisconsin_Breast_cancer_train.loc[malignantTrain, column_name] = 0

Wisconsin_Breast_cancer_train.head()

,Patient_ID,Diagnosis,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,f13,f14,f15,f16,f17,f18,f19,f20,f21,f22,f23,f24,f25,f26,f27,f28,f29,f30
0,909410,1,14.02,15.66,89.59,606.5,0.07966,0.05581,0.02087,0.02652,0.1589,0.05586,0.2142,0.6549,1.606,19.25,0.004837,0.009238,0.009213,0.010760,0.01171,0.002104,14.91,19.31,96.53,688.9,0.10340,0.1017,0.06260,0.08216,0.2136,0.06710
1,84358402,0,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,0.7572,0.7813,5.438,94.44,0.011490,0.024610,0.056880,0.018850,0.01756,0.005115,22.54,16.67,152.20,1575.0,0.13740,0.2050,0.40000,0.16250,0.2364,0.07678
2,8912284,1,12.89,15.70,84.08,516.6,0.07818,0.09580,0.11150,0.03390,0.1432,0.05935,0.2913,1.3890,2.347,23.29,0.006418,0.039610,0.079270,0.017740,0.01878,0.003696,13.90,19.69,92.12,595.6,0.09926,0.2317,0.33440,0.10170,0.1999,0.07127
3,90317302,1,10.26,12.22,65.75,321.6,0.09996,0.07542,0.01923,0.01968,0.1800,0.06569,0.1911,0.5477,1.348,11.88,0.005682,0.013650,0.008496,0.006929,0.01938,0.002371,11.38,15.65,73.23,394.5,0.13430,0.1650,0.08615,0.06696,0.2937,0.07722
4,914102,1,13.16,20.54,84.06,538.7,0.07335,0.05275,0.01800,0.01256,0.1713,0.05888,0.3237,1.4730,2.326,26.07,0.007802,0.020520,0.013410,0.005564,0.02086,0.002701,14.50,28.46,95.29,648.3,0.11180,0.1646,0.07698,0.04195,0.2687,0.07429

In [26]:
# How balanced is the training data?
without_bc = Wisconsin_Breast_cancer_train.Diagnosis.sum(axis=0)
with_bc = len(Wisconsin_Breast_cancer_train.Diagnosis) - without_bc
print(f"Without breast cancer = {without_bc}, with breast cancer = {with_bc}. {without_bc}:{with_bc}")

Without breast cancer = 58, with breast cancer = 42. 58:42

In [34]:
# How many features have missing entries in the training data?
Wisconsin_Breast_cancer_train.columns[Wisconsin_Breast_cancer_train.isnull().any()]

Index(['f21'], dtype='object')

In [36]:
# With f21, how many are missing?
Wisconsin_Breast_cancer_train['f21'].isnull().sum()

2

In [37]:
# How many features have missing entries in the test data?
Wisconsin_Breast_cancer_test.columns[Wisconsin_Breast_cancer_test.isnull().any()]

Index(['f21'], dtype='object')

In [38]:
# With f21, how many are missing?
Wisconsin_Breast_cancer_test['f21'].isnull().sum()

1

In [39]:
# Filling with mean in both training and test sets, 
#    note; assuming the more accurate mean is in the training set as it is larger
f21_mean_train = np.mean(Wisconsin_Breast_cancer_train['f21'])
Wisconsin_Breast_cancer_train['f21'] = Wisconsin_Breast_cancer_train['f21'].fillna(f21_mean_train)
Wisconsin_Breast_cancer_test['f21'] = Wisconsin_Breast_cancer_test['f21'].fillna(f21_mean_train)

In [40]:
### Split into X_train, Y_train, X_test, Y_test pairs
X_train = Wisconsin_Breast_cancer_train.values[:,2:]
Y_train = Wisconsin_Breast_cancer_train.values[:,1]
X_test = Wisconsin_Breast_cancer_test.values[:,2:]
Y_test = Wisconsin_Breast_cancer_test.values[:,1]

In [41]:
pd.DataFrame(X_train).head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29
0,14.02,15.66,89.59,606.5,0.07966,0.05581,0.02087,0.02652,0.1589,0.05586,0.2142,0.6549,1.606,19.25,0.004837,0.009238,0.009213,0.01076,0.01171,0.002104,14.91,19.31,96.53,688.9,0.1034,0.1017,0.0626,0.08216,0.2136,0.0671
1,20.29,14.34,135.1,1297.0,0.1003,0.1328,0.198,0.1043,0.1809,0.05883,0.7572,0.7813,5.438,94.44,0.01149,0.02461,0.05688,0.01885,0.01756,0.005115,22.54,16.67,152.2,1575.0,0.1374,0.205,0.4,0.1625,0.2364,0.07678
2,12.89,15.7,84.08,516.6,0.07818,0.0958,0.1115,0.0339,0.1432,0.05935,0.2913,1.389,2.347,23.29,0.006418,0.03961,0.07927,0.01774,0.01878,0.003696,13.9,19.69,92.12,595.6,0.09926,0.2317,0.3344,0.1017,0.1999,0.07127
3,10.26,12.22,65.75,321.6,0.09996,0.07542,0.01923,0.01968,0.18,0.06569,0.1911,0.5477,1.348,11.88,0.005682,0.01365,0.008496,0.006929,0.01938,0.002371,11.38,15.65,73.23,394.5,0.1343,0.165,0.08615,0.06696,0.2937,0.07722
4,13.16,20.54,84.06,538.7,0.07335,0.05275,0.018,0.01256,0.1713,0.05888,0.3237,1.473,2.326,26.07,0.007802,0.02052,0.01341,0.005564,0.02086,0.002701,14.5,28.46,95.29,648.3,0.1118,0.1646,0.07698,0.04195,0.2687,0.07429

In [42]:
pd.DataFrame(Y_train).head()

   0
0  1
1  0
2  1
3  1
4  1

In [43]:
print("X_train: \t", X_train.shape, "\nY_train: \t", Y_train.shape, "\nX_test: \t", X_test.shape, "\nY_test: \t", Y_test.shape)

X_train: 	 (100, 30)
Y_train: 	 (100,)
X_test: 	 (20, 30)
Y_test: 	 (20,)

In [46]:
### Normalize the training and testing data.
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_norm = scaler.fit_transform(X_train)
X_test_norm = scaler.transform(X_test)

<h1>Logistic regression</h1>

In [47]:
# Logistic Regression - L2 Regularisation

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score 
from sklearn.metrics import confusion_matrix

In [52]:
# Define Logistic Regression using L2 regularisation with lambda = 0.1
LR2 = LogisticRegression(penalty = 'l2', C=1/0.1) 
# The inverse of the regularisation strength, we need the inverse of the inverse, hence 1/0.1

In [58]:
# Fit the model
Y_train=Y_train.astype('int') # As Y_train is of type object which will throw an error.
LR2.fit(X_train_norm, Y_train)

LogisticRegression(C=10.0)

In [60]:
trained_predictions = LR2.predict(X_train_norm)

In [61]:
print("Accuracy Score = {}".format(np.round(accuracy_score(Y_train,trained_predictions)*100,decimals=2)),
      "\nPrecision Score = {}".format(precision_score(Y_train,trained_predictions)),
      "\nRecall Score = {}".format(recall_score(Y_train,trained_predictions)),
      "\nF1-score = {}".format(f1_score(Y_train,trained_predictions)),
      "\nConfusion Matrix = \n", confusion_matrix(Y_train,trained_predictions)
     )

Accuracy Score = 100.0
Precision Score = 1.0
Recall Score = 1.0
F1-score = 1.0
Confusion Matrix =
 [[42  0]
 [ 0 58]]

In [63]:
# Predict on test data
Y_test=Y_test.astype('int')
trained_predictions = LR2.predict(X_test_norm)
print("Accuracy Score = {}".format(np.round(accuracy_score(Y_test,trained_predictions)*100,decimals=2)),
      "\nPrecision Score = {}".format(precision_score(Y_test,trained_predictions)),
      "\nRecall Score = {}".format(recall_score(Y_test,trained_predictions)),
      "\nF1-score = {}".format(f1_score(Y_test,trained_predictions)),
      "\nConfusion Matrix = \n", confusion_matrix(Y_test,trained_predictions)
     )

Accuracy Score = 95.0
Precision Score = 0.9333333333333333
Recall Score = 1.0
F1-score = 0.9655172413793104
Confusion Matrix =
 [[ 5  1]
 [ 0 14]]